### ISSUE TITLE
Will it add support for custom void tags

### ISSUE THREAD

**Issue by luv-sic** [andrejewski/himalaya#105]
So it won't parse `<custom-tag />` to `<custom-tag></custom-tag>` . which is useful for parsing [vue template](https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended)
But, as you can see, `himalaya` is a html parser.....
I had implement this feature, could make a pull request if approved.

**Comment by luv-sic** [comment]
As i know, if it can't mark an AST node is void or not, like this:
```
interface Element extends Node {
  type: "element";
  tagName: string;
  children: [ Node ];
  attributes: [ Attribute ];
  void: boolean;
}
```
when `stringify` , it can't handle it appropriately.
```
if (node.void) {
   return `<${tagName}${formatAttributes(attributes)} />`
}
```

**Comment by andrejewski** [comment]
Both `parse` and `stringify` accept the same parse options so the AST doesn't need to encode it. 

Is the `parseDefaults.voidTags` sufficient for your use case? Example:

```js
const { parse, parseDefaults } = require('himalaya')
const parseOptions = {
  ...parseDefaults,
  voidTags: [...parseDefaults.voidTags, 'custom-tag']
}
const nodes = parse(htmlString, parseOptions)

console.log(stringify(nodes, parseOptions))
```

**Comment by luv-sic** [comment]
It's not sufficient, I want to build a `parser` and `stringify` for vue template.  So i don't know voids tags before actually parse the vue template.
Is there any other solutions, or I could fork it and make a version for vue template.
thx.

**Comment by andrejewski** [comment]
You can do a pre-processing step in your code looking for void tags up front and then pass that built up list to the parser. If that's not enough, I recommend forking as I probably won't get around to implementing this any time soon.

**Comment by luv-sic** [comment]
The Vue void tag has a trailing slash in it. `<custom-tag />`, so it may not work as expected.
Thank you for your heartful help, I will fork it.
