### ISSUE TITLE
tree.map is not a function

### ISSUE THREAD

**Issue by Isetnt2** [andrejewski/himalaya#108]
When doing window.himalaya.stringify() I get an error.
```
Uncaught TypeError: tree.map is not a function
    at toHTML (himalaya.js:1)
    at Object.stringify (himalaya.js:1)
    at Object.<anonymous> (script.js:113)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

**Comment by andrejewski** [comment]
You need to pass an array of nodes. I can't help further without seeing the input or a minimal test case.

**Comment by Isetnt2** [comment]
This is the code I'm trying to execute
`json2html(response.Table[0].todoData);` I do `console.log(response.Table[0].todoData)` before and it returns the array I parsed with 
`html2json(document.querySelector('.list-group').innerHTML)`

**Comment by andrejewski** [comment]
I need a full example, I don't know what `response.Table[0].todoData` is.

**Comment by Isetnt2** [comment]
It's a http get request that returns the value that I pushed to the server and ls the parsed value of 
```
html2json()
```
This is the currently parsed value on the server

**Comment by Isetnt2** [comment]
I've fixed my issue but replacing every JSON incompatible characters.
