### ISSUE TITLE
script and xmp issue when compile closing tag is not case sensitive

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#12]
issue when compile closing script tag is not case sensitive

`<script></SCRIPT>`  outputs:

```
js
  "content": "</SCRIPT></root>"
  "tagName": "script"
   "type": "Element"
```

What is this root?

Same happen for xmp tags:   `<xmp></xmp \n >`

**Comment by andrejewski** [comment]
This is fixed with #25.
