### ISSUE TITLE
img tag isn't self closing

### ISSUE THREAD

**Issue by afshawnlotfi** [andrejewski/himalaya#120]
Hi for the tag for img this syntax ```<img ... />``` where it closes without another img outputs ```<img ... >``` which is technically incorrect

**Comment by andrejewski** [comment]
> technically incorrect

Please provide W3C citations for claims about correctness. In any case, stringification is customizable in this regard: https://github.com/andrejewski/himalaya/blob/master/src/stringify.js#L25

`img` is a void tag, but you can opt not to include it. It's also easy to roll your own stringify methods.

Himalaya does not fully preserve malformed HTML.
