### ISSUE TITLE
what's the difference between himalaya and DOMParser?

### ISSUE THREAD

**Issue by bloody-ux** [andrejewski/himalaya#133]

**Comment by andrejewski** [comment]
If you mean https://developer.mozilla.org/en-US/docs/Web/API/DOMParser then:

- They both parse HTML but their outputs are different. Himalaya returns plain JavaScript objects which can easily be converted to and from JSON. DOMParser returns DOM trees, which are JavaScript objects which don't convert to JSON easily.
- DOMParser is part of the DOM, meaning it only exists in web browsers, not in backend JavaScript environments like Node (unless you use something like JSDOM to cover those differences up to an extent).
- DOMParser is going to be web browser specific; Chrome, Firefox, etc parse HTML (especially malformed HTML) in different ways and so the value you get from DOMParser may differ across these. Himalaya is written in JavaScript which would execute the same in any environment. It may do a better or worse job parsing compared to the browsers, but at least it will be consistent each time.
