### ISSUE TITLE
form tags

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#15]
As you can see in htmlparser2, formtags are a special case. https://github.com/fb55/htmlparser2/blob/master/lib/Parser.js#L26-L34

**Comment by andrejewski** [comment]
How does this relate to Himalaya?

**Comment by himalayafan** [comment]
It depends if you are supporting older browsers such as IE9+, older Android etc.

Example in Android<4.4 a checkbox should be "on", but it is not. So wrong output.

In older IE (not Edge) - default options tag doesn't get selected if selectedIndex are not accessed first. So the compilation would give a wrong output.

There list are longer.
	support.optSelected = opt.selected;

**Comment by andrejewski** [comment]
Nope, no plans to support the inconsistencies of older browsers. Himalaya parses HTML irrespective of how any single browser does its parsing.
