### ISSUE TITLE
properties issue

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#16]
In some cases HTML properties are set as an attribute. But a property should have a boolean value - true / false.

With himalaya it's possible to set a HTML property as  - example checked="checked" if we say that the "checked" is a property. It should have been checked="true"

**Comment by andrejewski** [comment]
[Are you sure?](http://stackoverflow.com/questions/7851868/whats-the-proper-value-for-a-checked-attribute-of-an-html-checkbox)

**Comment by himalayafan** [comment]
checked was just an example. If you look into real properties such as action, alt, controls, data etc
this issue occur. The list are longer.

**Comment by andrejewski** [comment]
Can you give me a concrete example?

**Comment by himalayafan** [comment]
node.action = true; // property

should be compiled into action=true if overloaded boolean or action="true" if not.

in your code this can be outputed as 'action="action"'  // not valid

You can also study this: https://github.com/nthtran/vdom-to-html

**Comment by andrejewski** [comment]
Show me a spec where action="action" is invalid. Why would anyone be setting [action](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/action) to a boolean value?

**Comment by himalayafan** [comment]
Again examples. 

https://html.spec.whatwg.org/

See this sections and you see what your parser doesn't support:

2.4.2 Boolean attributes

**Comment by andrejewski** [comment]
Himalaya seems to support the described behavior. If anyone can present a realistic example of a problem, I'll reopen this.
