### ISSUE TITLE
code never executed

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#17]
This part of the code never got executed?

https://github.com/andrejewski/himalaya/blob/master/index.js#L35-L38

And the closing tag section:

https://github.com/andrejewski/himalaya/blob/master/index.js#L91-L93

Maybe missing specs, but I tried this in browser and couldn't excute this lines.

**Comment by andrejewski** [comment]
Conditions exist when testing `parseUntil()` and `parseTag()` that don't for just calling `parse()` directly. For completeness in testing these functions separately, these cases are handled.
