### ISSUE TITLE
issues with attributes missing close quote

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#18]
issues with attributes missing close quote

 `<div a="1><span id="foo">xxx`

**Comment by joshuabuildsthings** [comment]
This looks like a really great project. I'm not sure what your position is on taking dependencies into the codebase, but this issue could probably be solved with something like HTML Tidy.

There's a NodeJS Wrapper for it here:
https://www.npmjs.com/package/htmltidy

**Comment by andrejewski** [comment]
I've left this issue open in case someone had a solution. For issues like these it comes down to the question of intent: should we assume the developer of the webpage is novice or knows what they are doing, more important how does it come rendered in a browser as I use Himalaya for parsing human readable webpages and if it breaks in a webpage they would have noticed to fix it if it was unintentional.

I looked at HTML Tidy and while it seems to be a good tool I don't think it belongs *inside* Himalaya. The biggest problem with integrating Tidy is it is asynchronous, I made Himalaya purposefully synchronous unlike many other parsers. Worse, the asynchronicity is the worst kind: spawning a child process, which is dangerous as with that we leave Node-land and have to deal with all the platform problems that might arise. I am not opposed to dependences, but they absolutely have to be synchronous JavaScript.

The good news is that if you want to use HTML Tidy beforehand you certainly can. A lot of the lacking of Himalaya with parser ambiguity and non-essential features is delegated to other modules that transform on the easier to use AST afterwards as well.

**Comment by ryanpiv** [comment]
Hi Andrew, in response to your assumption above about the competence of the developer, removing closing tags on items such as `<div id=1></div>` is normally done by parser apps when minifying HTML.  I'm not sure about how valid the syntax is, but I do know the browser can still interpret such an instance and when you assume HTML applications stretching thousands of lines, removing quotes is quite substantial over the life of the application.

It should be noted that a browser cannot parse `<div id=1 two 3></div>` as there is more than one value assigned to the attribute.

**Comment by andrejewski** [comment]
Yes, `<div id=1></div>` should be treated as `<div id="1"></div>`. This issue deals with the interpretations of the first line as either of the second two:
```
<div a="1><span id="foo">xxx
<div a="1><span id=" foo>xxx
<div a="1"><span id="foo">xxx
```

Much work is being done on the parser right now, which should address all issues being tracked.

**Comment by andrejewski** [comment]
Closing; this was never an immediate issue to anyone.
