### ISSUE TITLE
ES2015 template string support

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#2]
Would be a great idea I guess to add support for ES2015 template string

**Comment by andrejewski** [comment]
Seems unnecessary, what would be the benefit of Himalaya having access to the cooked expressions?

**Comment by himalayafan** [comment]
I just saw that a lot of libraries are adoption this now - template literals.

**Comment by andrejewski** [comment]
Himalaya parses text, all it needs is the text, so `himalaya.parse(string|template)` is adequate.
