### ISSUE TITLE
 form element isn't allowed inside phrasing content

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#20]
As stated in the specs:

*"For example, a form element isn't allowed inside phrasing content, because when parsed as HTML, a form element's start tag will imply a p element's end tag. Thus, the following markup results in two paragraphs, not one:

`<p>Welcome. <form><label>Name:</label> <input></form>`
It is parsed exactly like the following:

`<p>Welcome. </p><form><label>Name:</label> <input></form>`"*

However. If you try to parse this:

`<p>Welcome. <form><label>Name:</label> <input></form>`

your parser totaly screw this up,

**Comment by andrejewski** [comment]
Again, Himalaya is only concerned with giving an accurate representation of the HTML *given*. The difference between block level and span level elements is outside of the scope of this project. If someone needs this functionality they can build a transform on top of Himalaya quite easily.
