### ISSUE TITLE
volume attribute not parsed correctly

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#21]
Have a look here:
https://html.spec.whatwg.org/#effective-media-volume

See section 5.

'range 0.0 to 1.0'. In your parser, you can set all kind of numbers, also negative.

Also have a look at the start attribute. No negative numbers allowed

**Comment by andrejewski** [comment]
Himalaya is not going to keep track of acceptable values for every little thing. If someone intentionally made volume negative, Himalaya will parse it as such.
