### ISSUE TITLE
Problem on attributes with quotes in the value.

### ISSUE THREAD

**Issue by InDIOS** [andrejewski/himalaya#24]
Hi, great work with this library, but i have some problemes when i use the function toHTML in the translate.js. When an attribute value contain a single quotes, the quotes in the attribute value are single too, when, i believe, it should be double, the same happens with double quotes. I searched in the implementation and the solution is a simple `!` in the conditional in the line 13. Here is an example of the output when i use the parser and after of do somethig with the json, i use the toHTML method to come back to the HTML:
Original HTML
```html
<button @click="$store.dispatch('INCREMENT')" class="increment"> Increment</button>
```
and the Output is this
```html
<button @click='$store.dispatch('INCREMENT')' class='increment'> Increment</button>
```
This cause that the browser interpretate `@click='$store.dispatch('` and `increment')'` and this is an error.
I using this library and i hope that the issues can be solved soon. Thanks for the great work.

**Comment by andrejewski** [comment]
This is now fixed in 0.2.3; thank you for bringing this to my attention.
