### ISSUE TITLE
Option to skip whitespaces

### ISSUE THREAD

**Issue by armoucar** [andrejewski/himalaya#26]
```
Preserves Whitespace

Himalaya does not cut corners and returns an accurate representation of the HTML supplied.
```

Is there an option to 'cut corners'? :joy:

**Comment by andrejewski** [comment]
No, there is no builtin behavior; to accomplish this you can map recursively through Himalaya's output, taking each `children` child and using `content.trim()` to remove the whitespace. Then filter recursively, removing nodes with `content.length == 0`.

**Comment by armoucar** [comment]
that sounds pretty good to me, thanks :)

**Comment by andrejewski** [comment]
Here is an untested snippet for your and future humans' reference: https://gist.github.com/andrejewski/773487d4f4a46b16865405d7b74eabf9
