### ISSUE TITLE
empty attributes values are converted to 0.

### ISSUE THREAD

**Issue by armoucar** [andrejewski/himalaya#27]
from a html string to json

input:

    <div custom-attr=''></div>

output:

    [{"tagName":"div","attributes":{"customAttr":0},"children":[],"type":"Element"}]

So when converting back to html:

    <div custom-attr='0'></div>

**Comment by andrejewski** [comment]
Seen and will fix today.

**Comment by andrejewski** [comment]
Fix released as 0.2.3, please let me know if you find any more regressions.
