### ISSUE TITLE
Getting tags that are not defined

### ISSUE THREAD

**Issue by Skahrz** [andrejewski/himalaya#28]
I m actually playing with DOM -> AST -> DOM and I was wondering if there is anyway of getting informations related on tags that are not define by standard HTML tags.

For example, I m having the following string:

```
<div>
    <h1>Hi there</h1>
    <result></result>
</div>
```

But result is not defined, moreover its empty, and so I can't know that it exists inside the string inside the AST.

Any suggestions ? :)

**Comment by andrejewski** [comment]
Seen and will fix today.

**Comment by andrejewski** [comment]
I am having trouble reproducing your problem. Are you using the latest Himalaya version? Could you provide a full code example where you utilize `himalaya.parse()`, which shows the JSON AST you are receiving?

**Comment by Skahrz** [comment]
My bad.. I had an error in my code. Sorry about that useless issue

**Comment by andrejewski** [comment]
No problem, all the same I made http://andrejewski.github.io/himalaya so you can demo Himalaya without needing to install. Hopefully it will stop some issues from becoming Github issues.
