### ISSUE TITLE
While loop break condition (possibily) wrong when trying to find closing tag in 'parse' method

### ISSUE THREAD

**Issue by gioele-antoci** [andrejewski/himalaya#29]
Hey Chris,
Love the library. I am experiencing an issue when trying to crawl certain websites (e.g. [](https://www.twitter.com/android))

In the `parse` method I see this snippet: 
``` js 
while (--_len > -1) {
 if (tagName === stack[_len].tagName) {
     stack = stack.slice(0, _len);
     nodes = stack[_len - 1].children;
     break;
  }
}
```

I admit I don't fully understand what's going on, but wouldn't that break for `_len` = 0 (after decrement) ?
It will still enter the `while`, provided that enters the `if` condition, `stack` is going to be always an empty array.  On top of that we will try a lookup for `stack[-1]` which clearly doesn't have a `children` prop.

Am I missing something?
Thanks again

**Comment by andrejewski** [comment]
Could you please provide an isolated piece of HTML and the parser's output that causes your problem?

**Comment by gioele-antoci** [comment]
What do you mean by parser's output?

**Comment by andrejewski** [comment]
The JSON or the error reported

**Comment by gioele-antoci** [comment]
There is no error reported. himalaya is attempting to access the property of undefined.
Try to parse [http://www.golfchannel.com/](http://www.golfchannel.com/). It's hard to isolate a specific html snippet.

**Comment by andrejewski** [comment]
I won't do that much work. I'll be busy/offline for the next few days. If you do find your problem let me know. I use the relevant HTML/output for unit tests which is why I prefer that. Monday, if this isn't any more clear, I will try to make my own failing case and fix.

**Comment by gioele-antoci** [comment]
I can look further into it when I have some freetime. It's not a blocker for me, however you'd be the most efficient to pin it down.

**Comment by andrejewski** [comment]
Hopefully I have addressed your issue with the latest Himalaya version `0.2.5`. Please let me know if your exact underlying issue was not addressed.

**Comment by gioele-antoci** [comment]
I'll let you know later! Thanks :)
