### ISSUE TITLE
A lot of edge cases not handled correctly

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#3]
There are a lot of edge cases not handled correctly
- tagName with spaces will be compiled totaly wrong
- attributes with spaces will be compiled totaly wrong
- stand alone tagName freaks out -  `</div>`
- crazy tagName freaks out -  `<</div>>`
- unfinished tagName freaks out -  `<div>`
- self closing tag with spaces 
- self closing tag with spaces, trailing text
- normalize whitespace - e.g. `Line one\n<br>\t  \r\n\f  <br>\nline two<font><br> x </font>`
- brackets in attribute - e.g. `<div xxx="</div>">`
- unfinished comment. e.g.  `<!-- comment text` or `<!-- comment text --`  or  `<!-- comment text -`
- unfinished attribute. e.g `<div foo="`
- spaces in closing - e.g `< / div >` ( gives a weird output)
- if no value on an attribute, you setting it to - name = name. Not a valid HTML & XML syntax
  - namespaces - XML, Xlink etc. E.g. `<ns:tag>text</ns:tag>`
    This is only a few edge cases

**Comment by andrejewski** [comment]
Closing this issue because it should be broken up into smaller issues, if in fact they are issues. None of them should be as of #25.
