### ISSUE TITLE
How to parse html strings

### ISSUE THREAD

**Issue by sushant4anshu** [andrejewski/himalaya#30]
Like I have a data which fetched from website in html format like {"data" :"\<p>How are you?\</p>"}

How to convert these data to json using himalayas

**Comment by andrejewski** [comment]
That's not HTML, it is incorrectly formatted JSON. That is, assuming you mean to write:

```
{"data": "How are you?"}
```

**Comment by sushant4anshu** [comment]
Updated my question

**Comment by andrejewski** [comment]
```js
var response = {"data" :"<p>How are you?</p>"};
var json = require('himalaya').parse(response.data);
```

Please read the README. This question could have easily been answered by reading that.

**Comment by sushant4anshu** [comment]
giving TypeError: Object

*TypeError: Object <p>The Amazon Echo is a great smart speaker. It can
connect to a number of smart home devices, and let you control them with
voice; it can play your music for you, set alarms, and remind you about
things you ask it to. Plus, you can augment</p>*


*has no method 'startsWith'    at lex
(/home/sasuke/BeeBom/beebomapprestapi/node_modules/himalaya/lib/lexer.js:34:25)
  at lexer
(/home/sasuke/BeeBom/beebomapprestapi/node_modules/himalaya/lib/lexer.js:19:3)
  at Object.parse
(/home/sasuke/BeeBom/beebomapprestapi/node_modules/himalaya/lib/index.js:47:36)
  at Request._callback
(/home/sasuke/BeeBom/beebomapprestapi/app.js:605:24)    at
Request.self.callback
(/home/sasuke/BeeBom/beebomapprestapi/node_modules/request/request.js:186:22)
  at Request.EventEmitter.emit (events.js:98:17)    at Request.<anonymous>
(/home/sasuke/BeeBom/beebomapprestapi/node_modules/request/request.js:1081:10)
  at Request.EventEmitter.emit (events.js:95:17)    at
IncomingMessage.<anonymous>
(/home/sasuke/BeeBom/beebomapprestapi/node_modules/request/request.js:1001:12)
  at IncomingMessage.g (events.js:180:16)*

**Comment by andrejewski** [comment]
Now that is an actual bug. And I have created issue #31 to work on that separately (probably Monday).
