### ISSUE TITLE
TypeError: str.charAt is not a function

### ISSUE THREAD

**Issue by AJtwiss01** [andrejewski/himalaya#38]
getting the following error when running the basic setup 

v7.5.0/lib/node_modules/himalaya/lib/lexer.js:30
    var isText = str.charAt(state.cursor) !== '<';

TypeError: str.charAt is not a function]

**Comment by andrejewski** [comment]
What is "the basic setup"? Please provide code.

**Comment by AJtwiss01** [comment]
Here is  the code 
`var fs = require('fs')
var himalaya = require('himalaya')
var toHTML = require('himalaya/translate').toHTML

var html = fs.readFileSync('./webpage.html')
var json = himalaya.parse(html)
fs.writeFileSync('./webpage.html', toHTML(json))`

**Comment by andrejewski** [comment]
Use `fs.readFileSync('./webpage.html', {encoding: 'utf8'})` otherwise it returns a buffer. I'm sorry the README led you astray, it has been updated.

**Comment by AJtwiss01** [comment]
Thanks worked perfectly

**Comment by dennisaskeland** [comment]
I have the same issue, but when running via CLI. Basic HTML structure in input .html-file and index.json as output

**Comment by andrejewski** [comment]
@dennisaskeland and it is the [same problem](https://github.com/andrejewski/himalaya/blob/4012bd1c08f36f2f74b8ca34c36fd57dfd87d373/bin/himalaya.js#L61). Fix incoming.

**Comment by andrejewski** [comment]
@dennisaskeland your issue is fixed in `0.2.9`. Sorry for the trouble. I admit there are not good tests around the CLI. Thank you for commenting in this issue, it definitely was the right place.
