### ISSUE TITLE
Nested Unordered Lists Error

### ISSUE THREAD

**Issue by tompatros** [andrejewski/himalaya#39]
I was testing nested unordered lists and noticed that the "li" tag within the nested "ul" became a child of the top-level "ul" when parsing. Example below:

`<ul><li>TEXT<ul><li>SUBTEXT</li></ul></li></ul>`

Results in (note: triple asterisks added to highlight the JS object in question):

`[
  {
    "type": "Element",
    "tagName": "ul",
    "attributes": {},
    "children": [
      {
        "type": "Element",
        "tagName": "li",
        "attributes": {},
        "children": [
          {
            "type": "Text",
            "content": "TEXT"
          },
          {
            "type": "Element",
            "tagName": "ul",
            "attributes": {},
            "children": []
          }
        ]
      },
      ***{
        "type": "Element",
        "tagName": "li",
        "attributes": {},
        "children": [
          {
            "type": "Text",
            "content": "SUBTEXT"
          }
        ]
      }***
    ]
  }
]`

Expected (note: triple asterisks added to highlight the JS object in question):

`[
  {
    "type": "Element",
    "tagName": "ul",
    "attributes": {},
    "children": [
      {
        "type": "Element",
        "tagName": "li",
        "attributes": {},
        "children": [
          {
            "type": "Text",
            "content": "TEXT"
          },
          {
            "type": "Element",
            "tagName": "ul",
            "attributes": {},
            ***"children": [
             {
                "type": "Element",
                "tagName": "li",
                "attributes": {},
                "children": [
                   {
                      "type": "Text",
                      "content": "SUBTEXT"
                   }
                ]
              }
            ]***
          }
        ]
      }
    ]
  }
]`

What's interesting is it appears to only be limited to "ul" and "li" (at least in my limited testing). Similar markup with "div", "span" and a nested "div" seems to work fine.

`<div><span>SPAN TEXT<div>NESTED DIV TEXT</div></span></div>`

Confirmed in my own code and at https://jew.ski/himalaya/

**Comment by andrejewski** [comment]
Thanks @tompatros, I will try to get to this soon. What I suspect is going wrong here is [`closingTags`](https://github.com/andrejewski/himalaya/blob/928c3977df91bc6c9b5a97e6fff535b6bd9f4f3c/src/index.js#L16) is being used too strictly about auto-closing the `<li>`. We'll need a check of the parent `li` and child `li` depth to ensure auto-closing only happens when `<li>`s are direct parent-child. Hopefully, this is a bit more well defined so we don't have to riddle the code with conditionals. I will investigate soon. Thank you again for the detailed bug report.

**Comment by andrejewski** [comment]
The fix for this is released in v0.2.8. Thank you for your contribution @tompatros.
