### ISSUE TITLE
Error: Cannot find module './lexer'

### ISSUE THREAD

**Issue by valorloff** [andrejewski/himalaya#48]
Hi!
`meteor npm install himalaya`
```
import himalaya  from 'himalaya';
const parsed = himalaya.parse(html)
return parsed;
```
`Error: Cannot find module './lexer'`

**Comment by andrejewski** [comment]
A plain NPM install works for me. I am not aware of the differences between
 
```
npm install himalaya
```
and
```
meteor npm install himalaya
```

Please let me know. We do not test against any Meteor-specific technologies in this project.

**Comment by andrejewski** [comment]
Closing due to lack of response. Please reopen if this is an issue. However in general this project won't make any technical compromises for tooling that does not work with Node/npm systems.
