### ISSUE TITLE
Should support components?

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#5]
A must this days is components, and if Himalaya should be used with virtual DOM libraries, I suggest you add in support for components. Now you have a Text, Element, Comment node. 

What about adding in a 4th node? Component? I think that will drag users to this script.

**Comment by andrejewski** [comment]
Himalaya is used to parse HTML into a JSON representation of that HTML. Components are an abstraction provided by vdoms that are not actually apart of the HTML. Himalaya aims to be one-to-one with the HTML, not the higher abstraction. If someone needs a new node they can build on top of the spec to meet their needs.
