### ISSUE TITLE
Possible to port for the browser/client?

### ISSUE THREAD

**Issue by mgwhitfield** [andrejewski/himalaya#51]
It would be appealing to use this in a browser context.  Please and thank you :)

**Comment by andrejewski** [comment]
No need to port, Himalaya is browser ready. Use [dist/himalaya.js](https://github.com/andrejewski/himalaya/blob/master/docs/dist/himalaya.js) in a `<script/>` tag. This is how the [demo](http://andrejewski.github.io/himalaya) works.
