### ISSUE TITLE
Parser Ability To Handle Embedded Tables

### ISSUE THREAD

**Issue by bhreinb** [andrejewski/himalaya#57]
Hi There,

I have a minimum set of instructions to reproduce an issue I believe is with the parser. The set of steps to reproduce are the following:

1) Read Sample File Using i.e. 
`HtmlTemplate = fs.readFileSync(TemplateHtmlPath, {encoding: 'utf8'});`
2) Convert To Json i.e.
 `JsonTemplate = himalaya.parse(HtmlTemplate );`
3) Convert the Json Back To Html & Write To File i.e. 
`let Html = toHTML(JsonTemplate );`
`fs.writeFileSync(FinalHtmlPath, Html);`

The Html returned from toHTML(JsonTemplate) is very different to the HTML that was originally loaded into the program. I don't think the module currently handles embedded tables. Thoughts? I attach sample files (Test.html, script.js & style.css). As you can see from the sample html it contains embedded tables.

[Test.zip](https://github.com/andrejewski/himalaya/files/1241642/Test.zip)

**Comment by andrejewski** [comment]
Minimal case:

```html
<table><tbody><tr><td><table><tbody></tbody></table></td></tr></tbody></table>
```

I will look into this when I have time.

**Comment by bhreinb** [comment]
Lol it sure is. Thanks and let me know if you need any help reproducing this.

**Comment by andrejewski** [comment]
The fix has been released in `v0.2.11`. Thank you for your contribution.

**Comment by bhreinb** [comment]
thanks @andrejewski I got the latest 0.2.11 but this doesn't appear to be fixed as of yet....do you want me to send sample code and a test file? I think the minimal test scenario is missing embedding <tr> & <td> for example

**OLD**
`<table><tbody><tr><td><table><tbody></tbody></table></td></tr></tbody></table>`

**NEW**
`<table><tbody><tr><td><table><tbody><tr><td></td><td></td></tr></tbody></table></td></tr></tbody></table>`

The <tr> and <td> tags are been pushed to the top level table.

**Comment by andrejewski** [comment]
Ah, I see. I made the [parser demo](https://jew.ski/himalaya/) to help with issues so *usually* a HTML snippet is fine and I can load it up in the demo and see the problem. This will take a very similar fix and test cases, hopefully I can get this fixed when I find some time.

**Comment by bhreinb** [comment]
Hey @andrejewski thanks for the fix looks good. All the best.
