### ISSUE TITLE
no sanitizing or validation

### ISSUE THREAD

**Issue by himalayafan** [andrejewski/himalaya#6]
There is no validation in this code, is this going to be added with a good performance?

E.g. tagName should be validated. I never heard about tagName like ''#DIV=()" or "sPAn" etc. Or Chinese or Arabic letters.

As suggested here: https://github.com/andrejewski/himalaya/issues/5 Also validation would be needed. Components are upperCase letters.

**Comment by andrejewski** [comment]
The problem with validating tagName is that supported HTML tags change all the time and with Web Components coming out slowly but surely the namespace for tags is going to explode. Perhaps a alphanumeric including dashes and underscores check would be okay, though I do like how Himalaya at the moment parses without throwing much fuss.

**Comment by himalayafan** [comment]
I see the issue, but the examples on not valid tagNames will not be valid :) And same for numbers and other special characters

**Comment by andrejewski** [comment]
I have decided Himalaya will support any tag name. Validation can be handled by a module built on top of Himalaya.
