### ISSUE TITLE
formatStyles error

### ISSUE THREAD

**Issue by longjiarun** [andrejewski/himalaya#60]
if the style is 

```
background-image:url("https://wd.geilicdn.com/bj-vshop-216085684-1496287337836-345156715_900_900.jpg.webp?w=400&")
```

the formatStyles function will return

```
{
     "backgroundImage":"url(&quot",
     "http":"//wd.geilicdn.com/bj-vshop-216085684-1496287337836-345156715_900_900.jpg.webp?w=400&amp"
}
```

I debug the code, and find code. 

```
function formatStyles(str) {
     return str.trim().split(';').map(function (rule) {
          return rule.trim().split(':');
     }).reduce(function (styles, keyValue) {
……
```

**Comment by andrejewski** [comment]
Will fix, thanks for the issue. I'll be traveling all day tomorrow, but may have some time this weekend to get this fixed for you.

**Comment by andrejewski** [comment]
I was unable to figure how the `&quot;` and `&amp;` bits got into your example. Using latest, I do not use `encodeURIComponent()` anywhere in the library. The colon issue is fixed and will be out in the next patch release.

**Comment by longjiarun** [comment]
I find if background-image is base64
```
background-image: url(data:image/png;base64,iVBORw0
```
formatStyles will return 

```
"backgroundImage": "url(data:image/png"
```

also happen in formatStyles.

```
function formatStyles(str) {
  return str.trim().split(';').map(function (rule) {
```

**Comment by andrejewski** [comment]
Yeah, that's true. However this is not something I can support. Himalaya is an HTML parser not a CSS parser. It was my fault for including these extra preprocessing tasks in the original specification, over two years ago now. There will be a new spec for `v0.3` which does not do any special work, but for now I do not want to take on more work for what is almost certainty an edge-case.

**Comment by longjiarun** [comment]
Can you add option to config format style? If true then format style. FormatStyles is important for me, but i can do nothing now.

**Comment by andrejewski** [comment]
I don't recommend it but you can disable spec `v0` formatting. Replace [the `format` option](https://github.com/andrejewski/himalaya/blob/01112956646e49858e7916cfa12a1a9b395dc41e/src/index.js#L53) with `x => x` and you will have access to the underlying parsed HTML in a minimal data format. From there you can parse the plain `class` value using a real CSS parser.

I do not recommend that as the underlying parser data will change freely as fixed formats such as `v0` are there to guarantee the public specification(s).
