### ISSUE TITLE
Incorrectly parsing JSON when using innerText with <

### ISSUE THREAD

**Issue by figueiredo-lucas** [andrejewski/himalaya#71]
Hello,

I'm facing a problem in my code where some input made by an user have < and/or >.

As i tested, my input is: 

`"<span class="">
        >30 days and <= 120 days
</span>"`

and the json parser transforms it in:

```
{
    "type": "Element",
    "tagName": "span",
    "attributes": {
        "className": [
            ""
        ]
    },
    "children": [
        {
            "type": "Text",
            "content": "\n    \n        >30 days and "
        },
        {
            "type": "Element",
            "tagName": "=",
            "attributes": {
                "120": 120,
                "days": "days",
                "<": "<"
            },
            "children": []
        },
        {
            "type": "Text",
            "content": "pan>"
        }
    ]
}
```

That's a pretty specific scenario and anyways I already have a workaround for it. Just reported it so it could be tracked and later on fixed.

Thanks in advance!

**Comment by andrejewski** [comment]
I looked into this. My first reaction was that your `<` needed to be escaped, however looking at the [spec for HTML5 tag names](https://www.w3.org/TR/html5/syntax.html#syntax-tag-name) it appears only alphanumeric ascii characters are allowed. This means I can improve the parser for this case. However this introduces a new problem: the dash `-` is not an alphanumeric character which is used by many people for web/custom components. The question is where I draw the line when deviating from the spec.

**Comment by figueiredo-lucas** [comment]
The workaround I did was exactly that. As I said, it is a pretty specific scenario that does not happen very often (I've been using himalaya for nearly a year and it was the first time).
About the dash, unfortunately it looks like each case might need to be treated differently. By now, the dash is the only character deviating from the spec, right? 

Thanks for the reply and the effort!
