### ISSUE TITLE
SVG `viewBox` attribute not translated correctly

### ISSUE THREAD

**Issue by kbrsh** [andrejewski/himalaya#72]
When using the `viewBox` attribute with SVGs, and translating them back with `toHTML`, the attribute is incorrectly converted to `view-box`.

```html
<svg viewBox="0 0 100 100"></svg>
```

After parsing and translating back with `toHTML`, it is converted to:

```html
<svg view-box="0 0 100 100"></svg>
```

Edit: Also just wanted to thank you—Himalaya is a great project and I'm working on using it with my blog for MathJax typesetting support. It works by parsing the HTML and replacing a special syntax with the appropriate MathJax output. Keep up the great work!

**Comment by andrejewski** [comment]
Yeah, this is a problem with the Version 0 spec. I'm going to do I Himalaya version 1 which address this and other problems with a new spec. V1 was made available for early adopters, you should check out that specializes here: https://github.com/andrejewski/himalaya/blob/master/text/ast-spec-v1.md

**Comment by kbrsh** [comment]
Thanks! I'll check it out. Apologies if this issue was already documented somewhere. Feel free to close it if so.

**Comment by andrejewski** [comment]
It is documented and now with a [prerelease of Himalaya v1 available](https://github.com/andrejewski/himalaya/releases/tag/v1.0.0-0) you can try the newest spec using `npm install himalaya@next`.
