### ISSUE TITLE
Script help in python

### ISSUE THREAD

**Issue by shrishti01** [andrejewski/himalaya#75]
Hello,

Can you please help me out.
I also want to do the same thing that is converting html file in JSON file.
Can you provide me with python script of the same.
It will be very helpful

Thanks & Regards

**Comment by andrejewski** [comment]
I do not know Python well enough to write a performant/idiomatic port of Himalaya, nor have the time to do so. Your best bet is to use a Node executable script to call Himalaya with either a filename or text from `stdin` that returns JSON to `stdout`. With this you could spawn a process using Python and pipe the Node output back into your program to be parsed as JSON by your program.

There is a [CLI tool in Himalaya](https://github.com/andrejewski/himalaya/blob/0ffba1913728b331969c362b8ba74b0e4ede93c1/bin/himalaya.js) to help you get started writing such an executable, however please be aware that will no longer be supported in Himalaya v1 so you are better off creating your own thing and not relying on the CLI directly if you want to use v1.
