### ISSUE TITLE
 Couldn't find preset "stage-0" relative to directory during react native android build

### ISSUE THREAD

**Issue by StribMaxMarti** [andrejewski/himalaya#80]
First off, I'd like to express my gratitude for this library - it's made my life easier and proven very reliable.

My issue occurs when I'm building my react native project for android in release mode. During the bundle, the following error ocurrs:

`(...)/node_modules/himalaya/lib/index.js: Couldn't find preset "stage-0" relative to directory "(...)/node_modules/himalaya"`

This can be fixed by entering the `himalaya` directory, running `yarn`, and rebuilding. 

For whatever reason, my project yarn isn't fully provisioning the module. This could be an issue with yarn, however this is the only package I've experienced this issue with. I also suspect a mismatch in babel versions could be to blame - my project (and the majority of its dependencies) use version 6, while this library uses version 7.

**Comment by andrejewski** [comment]
@StribMaxMarti There was a [similar issue involving React Native](https://github.com/andrejewski/himalaya/issues/65) and the solution there was to upgrade your version of React Native.

I know with the instability of RN in general bumping versions mid-project is not ideal. If you can't bump, I'd suggest forking Himalaya and pointing to your own version with matching Babel deps if that is truly the issue. If you do this please report back, it may help others in the future.

**Comment by StribMaxMarti** [comment]
My project is currently running 0.52.0 - I will report back if upgrading RN or babel fixes the issue.

**Comment by andrejewski** [comment]
I am closing this issue. React Native has a history of being a weirdo. If anyone experiences similar pains, please open an issue with the React Native team (though try to find a smaller reproducible test case for them if possible).
