### ISSUE TITLE
Himalaya doesn't ignore extra closing tags

### ISSUE THREAD

**Issue by orballo** [andrejewski/himalaya#84]
Hi there!

I saw in the docs that `himalaya` should handle some weirdness like extra closing tags, however, it doesn't work in this case:

```
<div>
  <ul>
    <ul>
    </ul>
    </li> // this is the extra closing tag
  </ul>
</div>
<div class="will-not-parse">
</div>
```

It will parse all the content for the first `div`, but after that won't parse anything else. In this case, the second `div` won't be parsed.

Thanks!

**Comment by andrejewski** [comment]
Bug confirmed; I'll try to get to this soon.
